/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FoodsImport } from './routes/foods'
import { Route as CreatefoodImport } from './routes/create_food'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const FoodsRoute = FoodsImport.update({
  path: '/foods',
  getParentRoute: () => rootRoute,
} as any)

const CreatefoodRoute = CreatefoodImport.update({
  path: '/create_food',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create_food': {
      id: '/create_food'
      path: '/create_food'
      fullPath: '/create_food'
      preLoaderRoute: typeof CreatefoodImport
      parentRoute: typeof rootRoute
    }
    '/foods': {
      id: '/foods'
      path: '/foods'
      fullPath: '/foods'
      preLoaderRoute: typeof FoodsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CreatefoodRoute,
  FoodsRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create_food",
        "/foods"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create_food": {
      "filePath": "create_food.tsx"
    },
    "/foods": {
      "filePath": "foods.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
